# The MIT License (MIT)
#
# Copyright (c) 2016 Philippe Proulx <pproulx@efficios.com>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

version: '2.2'
options:
  gen-prefix-def: true
  gen-default-stream-def: true
metadata:
  $include:
    - stdint.yaml
    - stdfloat.yaml
    - stdmisc.yaml
    - lttng-ust-log-levels.yaml
  type-aliases:
    clock-int:
      $inherit: uint64
      property-mappings:
        - type: clock
          name: default
          property: value
     
  clocks:
    default:
      freq: 1000000000
      offset:
        seconds: 1434072888
      $return-ctype: uint64_t
  trace:
    $include: trace-basic.yaml
    byte-order: le
  streams:
    default:
      $default: true
      packet-context-type:
        class: struct
        fields:
          timestamp_begin: clock-int
          timestamp_end: clock-int
          packet_size: uint32
          content_size: uint32
          events_discarded: uint32
      event-header-type:
        class: struct
        fields:
          timestamp: clock-int
          id: uint16
      events:
        canbus_rcv:
          payload-type:
            class: struct
            fields:
              controller_id: string
              producer_id: string
              activity: string
              priority: uint32
              ts: uint32
              data0: uint8
              data1: uint8
              data2: uint8
              data3: uint8
              data4: uint8
              data5: uint8
              data6: uint8
              data7: uint8


